# NumPy Array functions

In [1]:
import numpy as np

In [4]:
#List to Numpy Array and printing the type of variable x
x = np.array([1,2,3,4])
print(type(x))

<class 'numpy.ndarray'>


In [5]:
print(x)

[1 2 3 4]


In [6]:
list = [1,2,3,4]
print(type(list))

<class 'list'>


In [8]:
#checking the time taken by list and NumPy array

%timeit [(j)**4  for j in range(1,8)]  # will run from 1 to 7 and will take power of 7 of each element in a list

4.03 µs ± 254 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
import numpy as np     #NumPy array is faster than list
%timeit np.arange(1,8)**4

2.76 µs ± 233 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
np.arange(1,8)**4   #NumPy array

array([   1,   16,   81,  256,  625, 1296, 2401], dtype=int32)

In [12]:
[(j)**4 for j in range(1,8)]   #List

[1, 16, 81, 256, 625, 1296, 2401]

In [14]:
# Creating a NumPy array

a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [16]:
l = []

for i in range(1,5):            #appending a NumPy array in a list 
    int_a = input("Enter the numbers you want to append in a list:")  #but as we are taking input we will get a string 
    l.append(int_a)
    
print(np.array(l))

Enter the numbers you want to append in a list:12
Enter the numbers you want to append in a list:12
Enter the numbers you want to append in a list:14
Enter the numbers you want to append in a list:15
['12' '12' '14' '15']


In [18]:
l = []

for i in range(1,5):            #appending a NumPy array in a list 
    int_a = int(input("Enter the numbers you want to append in a list:"))  #using int input to get the desired datatype in array
    l.append(int_a)
    
print(np.array(l))
print(type(l))

Enter the numbers you want to append in a list:12
Enter the numbers you want to append in a list:13
Enter the numbers you want to append in a list:1
Enter the numbers you want to append in a list:4
[12 13  1  4]
<class 'list'>


In [20]:
a = [1,2,3,4]

b= np.array(a)

print(b)
print("The dimension of our array is:",b.ndim)  #ndim function is used to check the dimension of an NumPy array

[1 2 3 4]
The dimension of our array is: 1


In [22]:
a = np.array([[1,2,3,4],[5,6,7,8]])  #The number of elements in list should be same for creating an NumPy array
#Array is created in a form of matrix
print(a)
print("The dimension of our array is:",a.ndim)

[[1 2 3 4]
 [5 6 7 8]]
The dimension of our array is: 2


In [23]:
#if the number of elements are not same it will return a list 
a = np.array([[1,2,3,4],[5,6,7]])  
#Array is created in a form of matrix
print(a)


[list([1, 2, 3, 4]) list([5, 6, 7])]
The dimension of our array is: 1


C:\Users\VIKASH R YADAV\AppData\Local\Temp\ipykernel_8184\1405161637.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3,4],[5,6,7]])


In [24]:
a = np.array([1,2,3,4],ndmin=10)  #ndmin is a fucntion to assign the nth dimension of a NumPy array
print(a)
print("The dimension of our array is:",a.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
The dimension of our array is: 10


# Creating a Numpy Array using NumPy function

In [26]:
# Array filled with 0's 

a = np.zeros(4)  #1-d array with 4 zeros
print(a)

print()

b = np.zeros((3,4)) #2-d array with 3 rows and 4 columns each having value as zero
print(b)


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
#Array filled with 1's

a = np.ones(4)  #1-d array with 4 ones
print(a)

print()

b = np.ones((3,4)) #2-d array with 3 rows and 4 columns each having value as one
print(b)


[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:
#Creating an Empty Array

a = np.empty(4)  #1-d array 
print(a)

print()

b = np.empty((3,4)) #2-d array with 3 rows and 4 columns and is an empty array
print(b)

#It prints the same NumPy array as above as it np.empty() function prints the last value assigned to the memory


[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
#Creating an array with a range of elements

a = np.arange(4)  #arange function takes the value from 0 to n-1
print(a)

[0 1 2 3]


In [38]:
#Array diagonal element with same number 1 or Identity MAtrix with Diagonal Elements as 1

a = np.eye(3)
print(a)

print()

b = np.eye(4,5)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [46]:
# Creating an Array with values that are spread linearly in a specified interval
 
a = np.linspace(1,20,num=10)  #num is used for spacing and num cannot be float
print(a)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [48]:
#Creating an Array with values that are spread linearly in a specified interval

a = np.arange(0,1,0.01)  #here, 0.01 is the spacing and it can be integer or float
a

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

# Creating a NumPy array with Random Numbers


In [49]:
# rand() function
import random as rd

a = np.random.rand(5)  #rand() fucntion randomly generates values between 0 to 1
print(a)               #gives a 1-d array

[0.75987465 0.06100512 0.96516289 0.74078615 0.41369685]


In [50]:
a = np.random.rand(2,4)  #rand() fucntion gives random values between 0 to 1 in 2 rows and 4 columns
print(a)                 #gives a 2-d array

[[0.20706115 0.19561183 0.08431826 0.73101061]
 [0.80817143 0.63279543 0.76068832 0.50175698]]


In [52]:
# randn() function

a = np.random.randn(5)    #randn() function randomly generates value close to zero and it can be positive or negative
print(a)

[ 0.19427708  1.1799573  -1.06464601  0.5791285   0.51383117]


In [54]:
# ranf() function 

a = np.random.ranf(5)  #ranf() generates random values in an array with a specified shape with interval [0.0,1.0)
print(a)                # It will generate values between 0 to 1 but it can be zero and it can't be 1


[0.539696   0.75193626 0.77674936 0.16901356 0.88912666]


In [56]:
# randint() function

a = np.random.randint(3,29,8)  #randint() generates a random value for a given range(minimum,maximum,total_values_generate)
print(a)

[ 3 23 22 14 10 20 27 18]


# Datatype of NumPy array

We can store a number, a string or both a number and a string in a NumPy Array

In [60]:
a = np.array([1,2,3,4])     #Integer datatype
print("Data type of the NumPy Array is:",a.dtype)

Data type of the NumPy Array is: int32


In [61]:
b = np.array([1.0,2.0,3.0,4.0])    #Float Datatype
print("Data type of the NumPy Array is:",b.dtype)

Data type of the NumPy Array is: float64


In [62]:
c = np.array(["a","b","c","d"])      #String Datatype
print("Data type of the NumPy Array is:",c.dtype)

Data type of the NumPy Array is: <U1


In [63]:
d = np.array([1,2,"a","c",4])     # String and integer datatype
print("Data type of the NumPy Array is:",d.dtype)

Data type of the NumPy Array is: <U11


In [65]:
e = np.array([1,2,"a","c",4,0,5.0,"c"])
print("Data type of the NumPy Array is:",a.dtype)

Data type of the NumPy Array is: int32


# Converting a NumPy array of one dtype to another dtype

In [69]:
a = np.array([1,2,3,4])
print("Data type of the NumPy Array is:",a.dtype)
print(a)

Data type of the NumPy Array is: int32
[1 2 3 4]


In [68]:
a = np.array([1,2,3,4],dtype=np.int8)     #converting it from int32 to int8
print("Data type of the NumPy Array is:",a.dtype)
print(a)

Data type of the NumPy Array is: int8
[1 2 3 4]


In [70]:
x = np.array([1,2,3,4],"f")     #converting it from int32 to float32
print("Data type of the NumPy Array is:",x.dtype)
print(x)

Data type of the NumPy Array is: float32
[1. 2. 3. 4.]


In [72]:
y = np.array([1,2,3,4],"U")     #converting it from int32 to unsigned integer
print("Data type of the NumPy Array is:",y.dtype)
print(y)

Data type of the NumPy Array is: <U1
['1' '2' '3' '4']


# Using one dtype as a function for other Numpy Array

In [74]:
x = np.array([1,2,3,4])  
y = np.float32(x)         #using x as a function over here to change the dtype from int32 to float32

print("Data type of the NumPy Array is:",x.dtype)
print("Data type of the NumPy Array is:",y.dtype)
      
print(x)
print(y)

Data type of the NumPy Array is: int32
Data type of the NumPy Array is: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [75]:
x = np.array([1,2,3,4])  
y = np.float32(x)         #using x as a function over here to change the dtype from int32 to float32
z = np.int_(y)            #using y as a function over here to change the dtype from float32 to int32

print("Data type of the NumPy Array is:",x.dtype)
print("Data type of the NumPy Array is:",y.dtype)
print("Data type of the NumPy Array is:",z.dtype)

print(x)
print(y)
print(z)

Data type of the NumPy Array is: int32
Data type of the NumPy Array is: float32
Data type of the NumPy Array is: int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [77]:
x1 = np.array([1,2,3,4])
x2 = x1.astype(float)       #astype() function is used to convert one datatype to another easily without using function

print(x1)
print(x2)

[1 2 3 4]
[1. 2. 3. 4.]


In [78]:
x1 = np.array([1,2,3,4])
x2 = x1.astype(complex)

print(x1)
print(x2)

[1 2 3 4]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


# Arithmetic Operations in NumPy arrays

In [79]:
x = np.array([1,2,3,4])   #Addition of 1-d Array
var_add = x+3
print(var_add)

[4 5 6 7]


In [80]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])   #Addition of Two NumPy Arrays

var_add = x + y
print(var_add)

[ 6  8 10 12]


In [82]:
x = np.array([1,2,3,4])
y = np.array([0,4,9,8])   #Subtraction of Two NumPy Arrays

var_add = x - y
print(var_add)

[ 1 -2 -6 -4]


In [84]:
x = np.array([1,2,3,4])
y = np.array([0,4,9,8])   #Multiplication of Two NumPy Arrays

var_add = x * y
print(var_add)

[ 0  8 27 32]


In [86]:
x = np.array([1,2,3,4])
y = np.array([2,4,9,8])   #Division of Two NumPy Arrays

var_add = x / y
print(var_add)

[0.5        0.5        0.33333333 0.5       ]


In [89]:
x = np.array([1,2,3,5])
y = np.array([2,4,9,15])   #Modulus of Two NumPy Arrays

var_add = x % y
print(var_add)

[1 2 3 5]


In [90]:
x = np.array([1,2,3,4])
y = np.array([0,4,9,8])   

var_add = np.add(x,y)    #Addition as a function of NumPy
print(var_add)

[ 1  6 12 12]


In [94]:
x = np.array([[1,2,3,4],[2,3,4,5]])
y = np.array([[0,4,9,8],[3,6,7,8]]) 

print(x)
print()
print(y)
print()

var_add = np.add(x,y)    #Addition as a function of NumPy for a 2D Array
print(var_add)

[[1 2 3 4]
 [2 3 4 5]]

[[0 4 9 8]
 [3 6 7 8]]

[[ 1  6 12 12]
 [ 5  9 11 13]]


# Arithmetic Functions in NumPy Arrays

In [105]:
a = np.array([1,2,3,4,5,6,2,9])

print("minimum:",np.min(a))
print("maximum:",np.max(a))
print()

print("Argmin:",np.argmin(a))   #gives the index value of the minimum
print("Argmax:",np.argmax(a))   #gives the index value of the maximum

print()
print("Square Root:",np.sqrt(a))  #gives the square root of the NumPy array


minimum: 1
maximum: 9

Argmin: 0
Argmax: 7

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 1.41421356 3.        ]


In [100]:
a = np.array([[3,9,1],[5,8,7]])

print("Maximum:",np.max(a,axis=0))   #axis=0 represent operations are being done in columns in 2d Array

Maximum: [5 9 7]


In [99]:
a = np.array([[3,4,1],[5,8,7]])

print("Maximum:",np.max(a,axis=1))  #axis=1 represent operations are being done in rows in 2d Array

Maximum: [4 8]


In [106]:
a = np.array([0.5,1,0,2])

print("Sin:",np.sin(a))
print("Cos:",np.cos(a))

Sin: [0.47942554 0.84147098 0.         0.90929743]
Cos: [ 0.87758256  0.54030231  1.         -0.41614684]


In [107]:
a = np.array([1,2,3,4])
print("Cumulative Sum:",np.cumsum(a))  #gives the cumulative sum of the NumPy array

Cumulative Sum: [ 1  3  6 10]


In [109]:
a = np.array([1,4,3,6,8])

print("Argsort:",np.argsort(a))  #Returns the indices that would sort an array

Argsort: [0 2 1 3 4]


# Shape and Reshaping in NumPy Arrays

In [110]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print()
print(a.shape)   #Prints the shape of the NumPy Array(Rows,Columns)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [111]:
a = np.array([1,2,3,4],ndmin=4)  #n-dimensional array
print(a)                         #ndmin function is used to make a n dimensional array
print()
print(a.shape)

[[[[1 2 3 4]]]]

(1, 1, 1, 4)


In [114]:
a = np.array([1,2,3,4,5,6])   #1-d array
print(a)
print("Dimension:",a.ndim)

print()

b = a.reshape(3,2)        #reshaped from 1-d array to 2-d array
print(b)
print("Dimension:",b.ndim)

[1 2 3 4 5 6]
Dimension: 1

[[1 2]
 [3 4]
 [5 6]]
Dimension: 2


In [117]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
print("Dimension:",a.ndim)    #1-d Array

print()

b = a.reshape(3,4)
print(b)
print("Dimension:",b.ndim)  #1-d array reshaped to 2-d array

print()

c = a.reshape(2,3,2)
print(c)
print("Dimension:",c.ndim) #1-d array reshaped to 3-d array

print()

d = c.reshape(-1) 
print(d)
print("Dimension:",d.ndim)  #Reshaping the 3-d array into 1-d array by using reshape(-1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension: 1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension: 2

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension: 3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension: 1


# Broadcasting

Broadcasting is an error which is generated when a NumPy array have 3 elements in it and another NumPy array contains 4 elements in it.

This error can be prevented if we have the following in our NumPy Arrays:
1.) Same Dimension
2.) If Dimensions are not same they should have at least one value same like (1,3) and (3,1) are present they have a value
    1 in both of them.

In [118]:
a = np.array([1,2,3])
print(a)
print("Dimension:",a.ndim)
print(a.shape)

print()

b = np.array([[1],[2],[3]])
print(b)
print("Dimension:",b.ndim)
print(b.shape)

print()

print(a + b)    #Addition is done as we are multiplying a m*n matrix with a n*p matrix resulting in m*p matrix
# the array which is generated is the maximum of the shape of the array as we move from right to left as 2*1 
#and 2*3 is given then moving from right to left we get an array of 2*3 as 2 is maximum from 2 and 2 and 3 is maximum
#between 1 and 3.

[1 2 3]
Dimension: 1
(3,)

[[1]
 [2]
 [3]]
Dimension: 2
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing In NumPy Array

In [120]:
a = np.array([1,2,3,4])
#             0,1,2,3 ---->Indexing
#            -4,-3,-2,-1---->Negative Indexing

print(a[1])                 #Indexing in 1-d Array
print(a[-2])

2
3


In [122]:
b = np.array([[4,5,6],[7,8,3]])
print(b)
print("Dimension:",b.ndim)

print()

print(b[0,2])              #Indexing in 2-d Array
print(b[1,1])

[[4 5 6]
 [7 8 3]]
Dimension: 2

6
8


In [129]:
c = np.array([[[1,2],[3,4]]])
print(c)
print("Dimension:",c.ndim)
print("Shape:",c.shape)

print(c[0,0,1])              #Indexing in 2-d Array

[[[1 2]
  [3 4]]]
Dimension: 3
Shape: (1, 2, 2)
2


# Slicing in NumPy Arrays

In [137]:
a = np.array([1,2,3,4,5,6])
#             0,1,2,3,4,5----->Indexing
print(a)
print("Dimensions:",a.ndim)
print(a.shape)
print()

print("2 to 5:",a[1:5])   #slicing [start:stop:step] 
print("2 to end:",a[1:])
print("start to 5:",a[:5])
print("Start to end:",a[:])
print("Reverse:",a[::-1])
print("Start to end with a step size of 1:",a[::2])

[1 2 3 4 5 6]
Dimensions: 1
(6,)

2 to 5: [2 3 4 5]
2 to end: [2 3 4 5 6]
start to 5: [1 2 3 4 5]
Start to end: [1 2 3 4 5 6]
Reverse: [6 5 4 3 2 1]
Start to end with a step size of 1: [1 3 5]


In [138]:
a = np.array([[4,5,6,7],[7,8,9,3]])
print(a)
print("Dimension:",a.ndim)
print("Shape:",a.shape)
print()

print("8 to 3:",a[1,1:])   #2-d array slicing indexing starts with 0 and 1 of 2d array first and then the elements in it

[[4 5 6 7]
 [7 8 9 3]]
Dimension: 2
Shape: (2, 4)

8 to 3: [8 9 3]


# Iterating NumPy Arrays

In [140]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
print()
for i in x:
    print(i)      #Iteration Process

[1 2 3 4 5 6 7 8 9]

1
2
3
4
5
6
7
8
9


In [142]:
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print()
for j in x:
    print(j)    #Iteration Process for 2d array
    
print()

for k in x:
    for l in k:    #Iteration process for the elements in the 2d array
        print(l)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [144]:
 x = np.array([[[1,2,3,4],[5,6,7,8]]])
print(x)
print("Dimensions:",x.ndim)
print()


for k in x:
    for l in k:    #Iteration process for the elements in the 3d array
        for i in l:
            print(i)

[[[1 2 3 4]
  [5 6 7 8]]]
Dimensions: 3

1
2
3
4
5
6
7
8


In [147]:
 x = np.array([[[1,2,3,4],[5,6,7,8]]])
print(x)
print("Dimensions:",x.ndim)
print()

for i in np.nditer(x):   #nditer() function is used to iterate the multidimensional array at once without using loops
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]
Dimensions: 3

1
2
3
4
5
6
7
8


In [148]:
 x = np.array([[[1,2,3,4],[5,6,7,8]]])
print(x)
print("Dimensions:",x.ndim)
print()

for i,d in np.ndenumerate(x):   #ndenumerate() function is used to iterate the array with the datatype(d) here
    print(i,d)                  # i is the indexing and d is the data

[[[1 2 3 4]
  [5 6 7 8]]]
Dimensions: 3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8


# Copy vs View In NumPy Array

1. View does not owns the data and copy owns the data.
2. The copy of an Array is a New Array whereas view is a view of a original array.
3. The change made in the copy does not reflect in the original array whereas any change made in the view will affect the 
   original array and the changes made in the original array will affect the view.

In [151]:
a = np.array([1,2,3,4])
b = a.copy()            #copy() function is used to copy the data from one array and use it in another array

a[1]=40                 #copy function does not gets affected by change in original data
print("Original:",a)
print("Copy:",b)

Original: [ 1 40  3  4]
Copy: [1 2 3 4]


In [152]:
x = np.array([9,8,7,6,5])
print("Original:",x)

x[1]=30
y = x.view()       #view() function is used to view the data 
print("View:",y)   #view function gets affected by change in original data


Original: [9 8 7 6 5]
View: [ 9 30  7  6  5]


# Join Array

In [157]:
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])
c = np.concatenate((a,b))      #Joining of two arrays for a 1-d array
print("Joining of two Arrays gives:",c)


Joining of two Arrays gives: [1 2 3 4 6 7 8 9]
0


In [159]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print()
print(b)
print()

c = np.concatenate((a,b),axis=1)   #joining the arrays along the rows
print("Joining of two Arrays gives:",c)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

Joining of two Arrays gives: [[1 2 5 6]
 [3 4 7 8]]


In [172]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print()
print(b)
print()

c = np.stack((a,b),axis=1)   
print("Joining of two Arrays gives:",c)

[1 2 3 4]

[5 6 7 8]

Joining of two Arrays gives: [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [174]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print()
print(b)
print()

c = np.hstack((a,b))    #joining along the rows
d = np.vstack((a,b))    #joining along the columns
e = np.dstack((a,b))    #joining along the height
print("Joining of two Arrays along the rows gives:",c)
print()
print("Joining of two Arrays along the columns gives:",d)
print()
print(e)    #Joining along the height
print("Dimensions of e:",e.ndim)


[1 2 3 4]

[5 6 7 8]

Joining of two Arrays along the rows gives: [1 2 3 4 5 6 7 8]

Joining of two Arrays along the columns gives: [[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]
Dimensions of e: 3


# Split Array
Splitting one array into multiple

In [178]:
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,3)      #np.array_split() is used to split the array and 3 is the number in which array is splitted
print("Splitting of array gives:",b)
print(type(b))
print(b[0])

Splitting of array gives: [array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [179]:
a = np.array([[1,2],[3,4],[5,6]])  #splitting of 2d array
b = np.array_split(a,3)      #np.array_split() is used to split the array and 3 is the number in which array is splitted
print("Splitting of array gives:",b)
print(type(b))
print(b[0])

Splitting of array gives: [array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>
[[1 2]]


In [185]:
a = np.array([[1,2],[3,4],[5,6]])  #splitting of 2d array
print(a)
print()

b = np.array_split(a,3,axis=1)      #splitting along then axis
print("Splitting of array gives:",b)
print()

c=a.astype(float)   #converting the dtype and conversion of dtype can be only done in NumPy Arrays & not in list
print(c)

[[1 2]
 [3 4]
 [5 6]]

Splitting of array gives: [array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]

[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Search Array

In [187]:
a = np.array([1,2,3,4,2,6,3,4,7,2])
#             0,1,2,3,4,5,6,7,8,9------->Indexing
b = np.where(a==2)
print("Indexes at which the number is present is:",b)


Indexes at which the number is present is: (array([1, 4, 9], dtype=int64),)


In [189]:
a = np.array([1,2,3,4,2,6,3,4,7,2])
#             0,1,2,3,4,5,6,7,8,9------->Indexing
b = np.where((a%2)==0)                          #We can also assign some operations in where functions
print("Indexes at which the number is present is:",b)


Indexes at which the number is present is: (array([1, 3, 4, 5, 7, 9], dtype=int64),)


# Search Sorted Array

In [191]:
a = np.array([1,2,3,4,7,8])
#             0,1,2,3,4,5--------->Indexing
b = np.searchsorted(a,6)   #shows the index where the number 6 should be placed in the array
print("Index of the number placed:",b)

Index of the number placed: 4


In [192]:
a = np.array([1,2,3,4,7,8])
#             0,1,2,3,4,5--------->Indexing
b = np.searchsorted(a,[5,6])   #shows the index where the number [5,6] should be placed in the array
print("Index of the number placed:",b)


Index of the number placed: [4 4]


# Sort function
Sorts the array containing numbers as well as the strings

In [193]:
a = np.array([1,4,2,77,56,34,90,45,7,35,745,73,9,23])  #1d array
print("Sorted Array:",np.sort(a))

Sorted Array: [  1   2   4   7   9  23  34  35  45  56  73  77  90 745]


In [194]:
a = np.array(['a','f','b','d','z','h'])   #Strings in list
print("Sorted Array:",np.sort(a))

Sorted Array: ['a' 'b' 'd' 'f' 'h' 'z']


In [195]:
a = np.array([[4,2,3],[23,6,45],[9,65,4]])
print("Sorted 2-d Array:",np.sort(a))

Sorted 2-d Array: [[ 2  3  4]
 [ 6 23 45]
 [ 4  9 65]]


# Filter Array
Subarray

In [197]:
a = np.array(['s','b','a','d','z'])
b = [True,False,False,True,False]
c = a[b]                  #Assiging true to the elements we want and false to the elements we don't want in an array
print("Filter Array:",c)
print(type(c))

Filter Array: ['s' 'd']
<class 'numpy.ndarray'>


# Arithmetic Functions in NumPy Arrays
1.Shuffle
2.Unique
3.Resize
4.Flatten
5.Ravel

In [199]:
a = np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(a)
print("Shuffling of array gives:",a)

Shuffling of array gives: [2 6 3 9 5 8 7 4 1]


In [202]:
a = np.array([1,2,3,4,5,2,3,4,5,2,6,87,2,9])
b = np.unique(a)
print("Unique Array:",b)   #Array without repetition of elements

Unique Array: [ 1  2  3  4  5  6  9 87]


In [203]:
a = np.array([1,2,3,4,5,2,3,4,5,2,6,87,2,9])
b = np.unique(a,return_index=True)  #return index with array as well
print("Unique Array:",b)   #Array without repetition of elements

Unique Array: (array([ 1,  2,  3,  4,  5,  6,  9, 87]), array([ 0,  1,  2,  3,  4, 10, 13, 11], dtype=int64))


In [204]:
a = np.array([1,2,3,4,5,2,3,4,5,2,6,87,2,9])
b = np.unique(a,return_index=True,return_counts=True)  #return index with array and count of elements in an array as well
print("Unique Array:",b)   #Array without repetition of elements

Unique Array: (array([ 1,  2,  3,  4,  5,  6,  9, 87]), array([ 0,  1,  2,  3,  4, 10, 13, 11], dtype=int64), array([1, 4, 2, 2, 2, 1, 1, 1], dtype=int64))


In [205]:
a = np.array([1,2,3,4,5,6])
b = np.resize(a,(2,3))       #2 Rows and 3 Columns
print("Resized Array:",b)    #Gives a 2D array


Resized Array: [[1 2 3]
 [4 5 6]]


In [207]:
a = np.array([[1,2],[3,4],[5,6]])
b = a.flatten()                         #flatten() and navel() functions are used to convert 2d array into 1d Array
print("Conversion of2-d array to 1-d array:",b)


[1 2 3 4 5 6]


In [212]:
a = np.array([[1,2],[3,4],[5,6]])
b = a.flatten(order="F")      #flatten() and navel() functions are used to convert 2d array into 1d Array
print(a)
print("Conversion of 2-d array to 1-d array:",b)   #order="F" converts 1d array columnwise
print("Ravel:",np.ravel(a,order="K"))


[[1 2]
 [3 4]
 [5 6]]
Conversion of 2-d array to 1-d array: [1 3 5 2 4 6]
Ravel: [1 2 3 4 5 6]


# Insertion in NumPy Array

In [213]:
a = np.array([1,2,3,4,5,6])
b = np.insert(a,2,40)         #np.insert(variable name,index,value)
print("Updated Array after Insertion:",b)

Updated Array after Insertion: [ 1  2 40  3  4  5  6]


In [214]:
a = np.array([1,2,3,4,5,6])
b = np.insert(a,(2,5),40)         #np.insert(variable name,index,value)
print("Updated Array after Insertion:",b)    

Updated Array after Insertion: [ 1  2 40  3  4  5 40  6]


In [215]:
a = np.array([1,2,3,4,5,6])
b = np.insert(a,(2,5),6.5)         #np.insert(variable name,index,value)
print("Updated Array after Insertion:",b)    #only integer value can be inserted no float value can be inserted

Updated Array after Insertion: [1 2 6 3 4 5 6 6]


In [218]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.insert(a,2,6,axis=0)    #row-wise insertion
print("Updated Array after Insertion:",b)


Updated Array after Insertion: [[1 2]
 [3 4]
 [6 6]
 [5 6]]


In [219]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.insert(a,2,[22,23],axis=0)    #row-wise insertion
print("Updated Array after Insertion:",b)   #.append() functions inserts the element at the end of an array

Updated Array after Insertion: [[ 1  2]
 [ 3  4]
 [22 23]
 [ 5  6]]


In [222]:
a = np.array([1,2,3,4,5,6])
b = np.append(a,6.5)         #np.append(variable name,index,value)
print("Updated Array after Insertion:",b)    #np.append() is used to add or insert float values at the end of an array

Updated Array after Insertion: [1.  2.  3.  4.  5.  6.  6.5]


# Deletion of an element from an array

In [223]:
a = np.array([1,2,3,4,5,6])
b = np.delete(a,2)        #np.delete(variable name,index)
print("Updated array after deletion: ",b)

Updated array after deletion:  [1 2 4 5 6]


# Matrix in NumPy Array

In [228]:
#Addition and Subtractrion of matrix and NumPy arrays gives us the same results

a = np.matrix([[1,2,3],[4,5,6]])
b = np.matrix([[1,2,3],[4,5,6]])
print("Matrix:",a)
print(type(a))
print()
print("Matrix Addition:",a + b)


Matrix: [[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>

Matrix Addition: [[ 2  4  6]
 [ 8 10 12]]


In [229]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
print("NumPy 2d array:",a)
print(type(a))
print()
print("NumPy Addition of arrays:",a + b)

NumPy 2d array: [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>

NumPy Addition of arrays: [[ 2  4  6]
 [ 8 10 12]]


In [232]:
#Dot Matrix Multiplication 
a = np.matrix([[1,2],[4,5]])
b = np.matrix([[1,2],[4,5]])
print("Dot Product Multiplication:",a.dot(b))

Dot Product Multiplication: [[ 9 12]
 [24 33]]


In [233]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
print("Multiplication of NumPy arrays:",a*b)

Multiplication of NumPy arrays: [[ 1  4  9]
 [16 25 36]]


# Matrix Functions in NumPy Arrays
1. Transpose
2. Swapaxes
3. Inverse
4. Power
5. Determinate

In [236]:
#Transpose of a Matrix
a = np.matrix([[1,2,3],[4,5,6]])
print("Matrix:",a)
print("Transpose of a Matrix:",np.transpose(a))  #np.transpose() takes the transpose of a matrix
print()
print("Transpose of a Matrix:",a.T)

Matrix: [[1 2 3]
 [4 5 6]]
Transpose of a Matrix: [[1 4]
 [2 5]
 [3 6]]

Transpose of a Matrix: [[1 4]
 [2 5]
 [3 6]]


In [238]:
#Swapping the axes of the matrix
a = np.matrix([[1,2,3],[4,5,6]])
print("Matrix:",a)
print()
print("Swapping the axes gives us:",np.swapaxes(a,0,1))  #swaps the axes

Matrix: [[1 2 3]
 [4 5 6]]

Swapping the axes gives us: [[1 4]
 [2 5]
 [3 6]]


In [239]:
a = np.matrix([[1,2],[3,4]])
print("Matrix:",a)
print()
print("Swapping the axes gives us:",np.swapaxes(a,0,1))  #swaps the axes

Matrix: [[1 2]
 [3 4]]

Swapping the axes gives us: [[1 3]
 [2 4]]


In [240]:
#Inverse of a Matrix
a = np.matrix([[1,2],[3,4]])
print("Matrix:",a)
print()
print("Inverse of a Matrix:",np.linalg.inv(a))  #np.linalg.inv(variable name) is used to inverse a matrix

Matrix: [[1 2]
 [3 4]]

Inverse of a Matrix: [[-2.   1. ]
 [ 1.5 -0.5]]


In [242]:
#Power of a Matrix
a = np.matrix([[1,2],[3,4]])
print("Matrix:",a)
print()
print("Power of a Matrix:",np.linalg.matrix_power(a,2))   #np.linalg.matrix_power(variable name,power)
print()
print("Power of a Matrix:",np.linalg.matrix_power(a,0))   #when power=0, we get an Identity Matrix
print()
print("Power of a Matrix:",np.linalg.matrix_power(a,-2))  #When power<0, Power of a Matrix = Inverse * Power

Matrix: [[1 2]
 [3 4]]

Power of a Matrix: [[ 7 10]
 [15 22]]

Power of a Matrix: [[1 0]
 [0 1]]

Power of a Matrix: [[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [244]:
#Determinate of a Matrix
a = np.matrix([[1,2,3],[3,4,5],[6,7,8]])
print("Matrix:",a)
print()
print("Determinate of a Matrix:",np.linalg.det(a))#np.linalg.det(variable name) is used to find the determinant of a matrix
print()


Matrix: [[1 2 3]
 [3 4 5]
 [6 7 8]]

Determinate of a Matrix: -3.7007434154172e-17

